#[macro_use]
extern crate rocket;

use rocket::{Build, Rocket};


#[get("/")]
fn index() -> &'static str {
    "hello from rocket."
}

/// the main function will be auto generated by the macro `#[launch]`
#[launch]
fn rocket() -> Rocket<Build> {
    rocket::build().mount("/", routes![index])
}