#[macro_use]
extern crate rocket;

use rocket::{Build, Rocket};

#[get("/")]
fn index() -> &'static str {
    "hello from rocket."
}

// the `main` function will be auto generated by the macro `#[launch]`
#[launch]
fn setup() -> Rocket<Build> {
    rocket::build().mount("/", routes![index])
}

// #[rocket::main]
// async fn main() -> Result<(), rocket::Error> {
//     {
//         let args = std::env::args();
//         println!("args: {:?}", args);
//     }
//
//     let _rocket = rocket::build()
//         .mount("/", routes![index])
//         .launch()
//         .await?;
//
//     Ok(())
// }